'use client';
import Link from 'next/link';
import {useState,useEffect} from 'react';
import {usePathname} from 'next/navigation';
import {ArrowUpRight,ArrowRight,ArrowDown,Menu,X} from 'lucide-react';
import {contact,motto,privacy,services} from '@/lib/content';

export function Brand(){return <Link className="brand" href="/" aria-label="CIRS-Conseil Inc., accueil"><span className="brand-name">CIRS</span><span className="brand-sub">Conseil<span> Inc.</span></span></Link>}

const navItems=[{href:'/#apropos',label:'À propos',id:'apropos'},{href:'/equipe/',label:'Équipe',id:''},{href:'/#expertises',label:'Expertises',id:'expertises'},{href:'/#services',label:'Services',id:'services'},{href:'/articles/',label:'Articles',id:''},{href:'/evenements/',label:'Événements',id:''}];

// En-tête collant : transparent sur le hero de l’accueil, il se rétracte au défilement vers le bas
// pour ne jamais masquer les titres et réapparaît dès que l’on remonte.
export function Header({overlay=false}:{overlay?:boolean}){
  const[open,setOpen]=useState(false);const[scrolled,setScrolled]=useState(false);const[hidden,setHidden]=useState(false);const[section,setSection]=useState('');
  const pathname=usePathname();
  useEffect(()=>{let last=window.scrollY;const onScroll=()=>{const y=window.scrollY;setScrolled(y>8);setHidden(y>last&&y>320);last=y};onScroll();window.addEventListener('scroll',onScroll,{passive:true});return()=>window.removeEventListener('scroll',onScroll)},[]);
  useEffect(()=>{if(pathname!=='/')return;const els=navItems.flatMap(n=>{const el=n.id?document.getElementById(n.id):null;return el?[el]:[]});const io=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting)setSection(e.target.id)},{rootMargin:'-45% 0px -50% 0px'});els.forEach(el=>io.observe(el));return()=>io.disconnect()},[pathname]);
  useEffect(()=>{document.body.style.overflow=open?'hidden':'';return()=>{document.body.style.overflow=''}},[open]);
  const close=()=>setOpen(false);
  const isActive=(n:typeof navItems[number])=>n.id?pathname==='/'&&section===n.id:pathname.startsWith(n.href);
  const cls=['header',overlay&&!scrolled&&!open&&'on-dark',scrolled&&'scrolled',hidden&&!open&&'hidden',open&&'menu-open'].filter(Boolean).join(' ');
  return <header className={cls}><div className="wrap header-inner"><Brand/><nav aria-label="Navigation principale" className={open?'nav open':'nav'}>{navItems.map(n=><Link key={n.href} onClick={close} href={n.href} className={isActive(n)?'active':undefined} aria-current={isActive(n)?'page':undefined}>{n.label}</Link>)}<Link className="nav-contact" onClick={close} href="/contact/">Contact</Link><div className="nav-footer"><a href={'mailto:'+contact.email}>{contact.email}</a><a href={contact.phoneHref}>{contact.phone}</a></div></nav><button className="menu-toggle" aria-label={open?'Fermer le menu':'Ouvrir le menu'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X size={22} strokeWidth={1.5}/>:<Menu size={22} strokeWidth={1.5}/>}</button></div></header>
}

// En-tête des pages intérieures : étiquette, grand titre, chapeau.
export function PageIntro({label,title,children,crumb}:{label:string;title:React.ReactNode;children?:React.ReactNode;crumb?:string}){return <section className="page-intro wrap"><div className="rail"><span className="label">{label}</span>{crumb&&<Link className="crumb" href="/">← Accueil</Link>}</div><div className="page-intro-body"><h1>{title}</h1>{children&&<div className="page-intro-text">{children}</div>}</div></section>}

export function Footer(){return <footer className="footer"><div className="wrap footer-top"><div className="footer-brand"><Brand/><p className="footer-motto">{motto}</p><p>Cabinet de conseil canado-québécois en stratégie et affaires publiques.</p></div><div className="footer-col"><span className="label">Coordonnées</span><a href={'mailto:'+contact.email}>{contact.email}</a><a href={contact.phoneHref}>{contact.phone}</a><a href={contact.whatsappHref} target="_blank" rel="noopener noreferrer">WhatsApp {contact.whatsapp}</a><span>{contact.locations.join(' · ')} — {contact.remote.toLowerCase()}</span></div><div className="footer-col"><span className="label">Explorer</span><Link href="/#apropos">À propos</Link><Link href="/equipe/">Équipe</Link><Link href="/#expertises">Expertises</Link><Link href="/articles/">Articles</Link><Link href="/evenements/">Événements</Link><Link href="/contact/">Contact</Link></div></div><div className="wrap footer-privacy" id="confidentialite"><span className="label">Confidentialité</span><p>{privacy}</p></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} CIRS-Conseil Inc.</span><a href="#top">Haut de page ↑</a></div></footer>}

export function ContactForm(){const[sent,setSent]=useState(false);return <form className="contact-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const subject=`Demande CIRS-Conseil — ${f.get('topic')}`;const body=`Nom : ${f.get('name')}\nCourriel : ${f.get('email')}\nOrganisation : ${f.get('company')||'—'}\nTéléphone : ${f.get('phone')||'—'}\nBesoin : ${f.get('topic')}\n\n${f.get('message')}`;window.location.href=`mailto:${contact.email}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;setSent(true)}}><div className="form-grid"><label><span>Nom complet</span><input name="name" required autoComplete="name" maxLength={120}/></label><label><span>Courriel professionnel</span><input type="email" name="email" required autoComplete="email" maxLength={180}/></label><label><span>Organisation</span><input name="company" autoComplete="organization" maxLength={180}/></label><label><span>Téléphone <em>facultatif</em></span><input type="tel" name="phone" autoComplete="tel" maxLength={40}/></label></div><label><span>Votre besoin</span><select name="topic" defaultValue={services[0]?.title}>{services.map(s=><option key={s.title}>{s.title}</option>)}<option>Conférence ou intervention</option><option>Autre demande</option></select></label><label><span>Vos enjeux</span><textarea required name="message" minLength={15} maxLength={5000} rows={5} placeholder="Contexte, marchés concernés, échéances…"/></label><div className="form-actions"><button className="button" type="submit">Envoyer la demande <ArrowRight size={18} strokeWidth={1.5}/></button><p className="form-note">L’envoi ouvre votre messagerie avec un courriel prérempli adressé à {contact.email}. Aucune donnée n’est stockée sur ce site. <a href="#confidentialite">Confidentialité</a></p></div>{sent&&<p role="status" className="form-result">Votre messagerie devrait s’ouvrir. Sinon, écrivez-nous directement à <a href={'mailto:'+contact.email}>{contact.email}</a> ou appelez le <a href={contact.phoneHref}>{contact.phone}</a>.</p>}</form>}

export {ArrowUpRight,ArrowRight,ArrowDown};
