'use client';
import Link from 'next/link';
import {useState,useEffect} from 'react';
import {usePathname} from 'next/navigation';
import {ArrowUpRight,ArrowRight,Plus,Minus,Menu,X,Globe2,Landmark,BriefcaseBusiness,Users,Leaf,ChartColumn,ChevronDown,Mail,Phone,MessageCircle,MapPin,Laptop} from 'lucide-react';
import {services,sectors,regions,contact,motto,privacy} from '@/lib/content';

export function Brand({light=false}:{light?:boolean}){return <Link className={light?'brand light':'brand'} href="/" aria-label="CIRS-Conseil Inc., accueil"><img className="brand-logo" src="/cirs-logo.png" alt="" width="56" height="56"/><span className="brand-text"><span className="brand-name">CIRS-Conseil <span>Inc.</span></span><span className="brand-sub">Stratégie et affaires publiques</span></span></Link>}

export function TopBar(){return <div className="topbar"><div className="container topbar-inner"><span className="topbar-motto">{motto}</span><div className="topbar-links"><a href={'mailto:'+contact.email}><Mail size={14}/>{contact.email}</a><a href={contact.phoneHref}><Phone size={14}/>{contact.phone}</a><a href={contact.whatsappHref} target="_blank" rel="noopener noreferrer"><MessageCircle size={14}/>WhatsApp</a></div></div></div>}

const navItems=[{href:'/#apropos',label:'À propos',id:'apropos'},{href:'/#expertises',label:'Expertises',id:'expertises'},{href:'/#services',label:'Services',id:'services'},{href:'/articles/',label:'Articles',id:''},{href:'/evenements/',label:'Événements',id:''}];

// En-tête collant qui se rétracte au défilement vers le bas pour ne jamais masquer les titres,
// et réapparaît dès que l’on remonte.
export function Header(){
  const[open,setOpen]=useState(false);const[scrolled,setScrolled]=useState(false);const[hidden,setHidden]=useState(false);const[section,setSection]=useState('');
  const pathname=usePathname();
  useEffect(()=>{let last=window.scrollY;const onScroll=()=>{const y=window.scrollY;setScrolled(y>8);setHidden(y>last&&y>260);last=y};onScroll();window.addEventListener('scroll',onScroll,{passive:true});return()=>window.removeEventListener('scroll',onScroll)},[]);
  useEffect(()=>{if(pathname!=='/')return;const els=navItems.flatMap(n=>{const el=n.id?document.getElementById(n.id):null;return el?[el]:[]});const io=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting)setSection(e.target.id)},{rootMargin:'-45% 0px -50% 0px'});els.forEach(el=>io.observe(el));return()=>io.disconnect()},[pathname]);
  const close=()=>setOpen(false);
  const isActive=(n:typeof navItems[number])=>n.id?pathname==='/'&&section===n.id:pathname.startsWith(n.href);
  return <><TopBar/><header className={['header',scrolled&&'scrolled',hidden&&!open&&'hidden'].filter(Boolean).join(' ')}><div className="container header-inner"><Brand/><nav aria-label="Navigation principale" className={open?'nav open':'nav'}>{navItems.map(n=><Link key={n.href} onClick={close} href={n.href} className={isActive(n)?'active':undefined} aria-current={isActive(n)?'page':undefined}>{n.label}</Link>)}<Link className="nav-contact" onClick={close} href="/contact/">Nous contacter <ArrowUpRight size={16}/></Link></nav><button className="menu-toggle" aria-label={open?'Fermer le menu':'Ouvrir le menu'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></header></>
}

export function ContactDetails({dark=false}:{dark?:boolean}){return <ul className={dark?'contact-details dark':'contact-details'}><li><Mail size={19}/><span><small>Courriel</small><a href={'mailto:'+contact.email}>{contact.email}</a></span></li><li><Phone size={19}/><span><small>Téléphone</small><a href={contact.phoneHref}>{contact.phone}</a></span></li><li><MessageCircle size={19}/><span><small>WhatsApp</small><a href={contact.whatsappHref} target="_blank" rel="noopener noreferrer">{contact.whatsapp}</a></span></li><li><MapPin size={19}/><span><small>Implantation</small>{contact.locations.join(' · ')}</span></li><li><Laptop size={19}/><span><small>Modalités</small>{contact.remote}</span></li></ul>}

export function Footer(){return <footer><div className="container footer-top"><div className="footer-brand"><Brand light/><p className="footer-motto">{motto}</p><p>Cabinet de conseil canado-québécois en stratégie et affaires publiques.</p></div><div className="footer-col"><span className="footer-title">Coordonnées</span><a href={'mailto:'+contact.email}>{contact.email}</a><a href={contact.phoneHref}>Tél. : {contact.phone}</a><a href={contact.whatsappHref} target="_blank" rel="noopener noreferrer">WhatsApp : {contact.whatsapp}</a><span>{contact.locations.join(' | ')} · {contact.remote}</span></div><div className="footer-col"><span className="footer-title">Explorer</span><Link href="/#expertises">Domaines d’expertise</Link><Link href="/#services">Services</Link><Link href="/articles/">Articles & analyses</Link><Link href="/evenements/">Conférences & événements</Link><Link href="/contact/">Nous contacter</Link><a href="#confidentialite">Confidentialité</a></div></div><div className="container footer-privacy" id="confidentialite"><span className="footer-title">Confidentialité</span><p>{privacy}</p></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} CIRS-Conseil Inc.</span><span>Stratégie et affaires publiques · Québec · International</span><a href="#top">Retour en haut ↑</a></div></footer>}

const serviceIcons=[Landmark,BriefcaseBusiness,Users,Leaf,ChartColumn];
export function Services(){const[active,setActive]=useState<number|null>(0);return <div className="service-list">{services.map((s,i)=>{const Icon=serviceIcons[i];return <article className={active===i?'service active':'service'} key={s.title}><h3><button aria-expanded={active===i} aria-controls={'service-'+i} onClick={()=>setActive(active===i?null:i)}><span className="service-icon"><Icon size={24} strokeWidth={1.5}/></span><span>{s.title}<small>{s.short}</small></span><span className="expand">{active===i?<Minus size={20}/>:<Plus size={20}/>}</span></button></h3><div id={'service-'+i} hidden={active!==i} className="service-detail"><p>{s.description}</p><div className="deliverables"><span>EXPERTISES MOBILISÉES</span><ul>{s.items.map(item=><li key={item}>{item}</li>)}</ul></div></div></article>})}</div>}

export function Sectors(){const[active,setActive]=useState(0);return <div className="sector-layout"><div className="sector-list" role="tablist" aria-label="Secteurs d’intervention" aria-orientation="vertical">{sectors.map((s,i)=><button key={s.title} role="tab" aria-selected={active===i} id={'sector-tab-'+i} aria-controls={'sector-panel-'+i} tabIndex={active===i?0:-1} onKeyDown={e=>{if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();const next=(i+(e.key==='ArrowDown'?1:-1)+sectors.length)%sectors.length;setActive(next);document.getElementById('sector-tab-'+next)?.focus()}}} onClick={()=>setActive(i)}><span>0{i+1}</span>{s.title}<ArrowUpRight size={20}/></button>)}</div><div role="tabpanel" id={'sector-panel-'+active} aria-labelledby={'sector-tab-'+active} className="sector-panel"><span className="eyebrow">VOTRE SECTEUR, NOTRE ATTENTION</span><span className="sector-large-number">0{active+1}</span><h3>{sectors[active].title}</h3><p>{sectors[active].text}</p><Link className="text-link" href="/contact/">Échanger sur vos enjeux <ArrowRight size={17}/></Link></div></div>}

export function Regions(){const[active,setActive]=useState(0);return <div className="regions"><div className="region-choices">{regions.map((r,i)=><button key={r.name} className={active===i?'selected':''} aria-pressed={active===i} onClick={()=>setActive(i)}><span>0{i+1}</span>{r.name}<ArrowUpRight size={20}/></button>)}</div><div className="region-copy" aria-live="polite"><Globe2 size={46} strokeWidth={.8}/><h3>{regions[active].countries}</h3><p>{regions[active].text}</p><span className="region-note">IMPLANTÉS AU QUÉBEC · TRAVAIL À DISTANCE</span></div></div>}

export function ContactForm(){const[sent,setSent]=useState(false);return <form className="contact-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const subject=`Demande CIRS-Conseil — ${f.get('topic')}`;const body=`Nom : ${f.get('name')}\nCourriel : ${f.get('email')}\nOrganisation : ${f.get('company')||'—'}\nTéléphone : ${f.get('phone')||'—'}\nBesoin : ${f.get('topic')}\n\n${f.get('message')}`;window.location.href=`mailto:${contact.email}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;setSent(true)}}><div className="form-grid"><label>Nom complet<input name="name" required autoComplete="name" maxLength={120} placeholder="Votre nom"/></label><label>Courriel professionnel<input type="email" name="email" required autoComplete="email" maxLength={180} placeholder="vous@organisation.com"/></label></div><div className="form-grid"><label>Organisation<input name="company" autoComplete="organization" maxLength={180} placeholder="Votre organisation"/></label><label>Téléphone<input type="tel" name="phone" autoComplete="tel" maxLength={40} placeholder="Facultatif"/></label></div><label>Votre besoin<select name="topic" defaultValue={services[0].title}>{services.map(s=><option key={s.title}>{s.title}</option>)}<option>Conférence ou intervention</option><option>Autre demande</option></select></label><label>Quelques mots sur vos enjeux<textarea required name="message" minLength={15} maxLength={5000} rows={5} placeholder="Contexte, marchés concernés, échéances…"/></label><p className="form-note">L’envoi ouvre votre messagerie avec un courriel prérempli adressé à {contact.email}. Aucune donnée n’est stockée sur ce site. <a href="#confidentialite">Confidentialité</a></p><button className="button dark" type="submit">Envoyer ma demande <ArrowRight size={18}/></button>{sent&&<p role="status" className="form-result">Votre messagerie devrait s’ouvrir. Sinon, écrivez-nous directement à <a href={'mailto:'+contact.email}>{contact.email}</a> ou appelez le <a href={contact.phoneHref}>{contact.phone}</a>.</p>}</form>}

export {ArrowUpRight,ArrowRight,ChevronDown};
